### ISSUE TITLE
Bug with "prompt" and "confirm" blocks

### ISSUE THREAD

**Issue by Spaceflyer234** [Spaceflyer234/scratch-extension#1]
If you show the "prompt" or "confirm" block it will keep making a popup window until it is hidden.

**Comment by BoomerScratch** [comment]
It's not technically a bug, because it constantly refreshes the value (it runs the script for the block again), making that happen.

**Comment by Spaceflyer234** [comment]
> It's not technically a bug, because it constantly refreshes the value (it runs the script for the block again), making that happen.

Okay, but is there a way you can hide the button to show/hide it?

**Comment by BoomerScratch** [comment]
> > It's not technically a bug, because it constantly refreshes the value (it runs the script for the block again), making that happen.
> 
> Okay, but is there a way you can hide the button to show/hide it?

Yes, but people could put the "confirm" block in the when block, like this:
![image](https://user-images.githubusercontent.com/60622217/81292305-a3123000-906b-11ea-971b-9355c9be45ab.png)
